# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1
[default]

[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "sam-hello-lambda"
region = "ap-northeast-1"
profile = "serverless"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.package]
[default.package.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
