version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "sam-hello-lambda"
region = "ap-northeast-1"
profile = "serverless"
capabilities = "CAPABILITY_IAM"
image_repositories = []
