version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-native-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "sam-native-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
